config/routes.rb
Textapp::Application.routes.draw do
  devise_for :users

  resources :messages, :only => [:index, :new, :create, :show]
  root to: 'messages#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

  validates :to, :presence => true
  validates :from, :presence => true
  validates :body, :presence => true

private

  def send_message
    response = RestClient::Request.new(
      :method => :post,
      :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_AUTH_TOKEN'],
      :payload => { :Body => body,
                    :To => to,
                    :From => from }
  ).execute
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private


  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation,
                                 :remember_me)
  end

  def authorize
    redirect_to root_path, alert: "Please sign in to send a message." if current_user.nil?
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authorize, only: [:create, :show]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_path
    else
      render
    end
  end

  def show
    @message = Message.find(params[:id])
  end

private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- Copyright 2014: J. Vogelsberg & Kathryn Hough  -->
<head>
  <title>Breaker-Breaker!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div id="wrap">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-linear">
        <a href="http://www.jasonvogelsberg.com/"><img src="/bb_title.png" class="brand" alt="Breaker Breaker Logo" ></a>
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li>Logged in as <strong><%= current_user.email %></strong> </li>
                <li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
                <li><%= link_to "Send a message", new_message_path %> </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %> </li>
                <li><%= link_to "Login", new_user_session_path %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="span9">
          <br/>
          <div class="white_back">
            <%= flash[:notice] %>
            <h3><em> <%= flash[:alert] %> </em></h3>
          </div>
          <br/>
          <div class="white_back">
            <%= yield %>
          </div>
        </div>
        <div class="span4">
          <div class="white_back">
          <h4>How Does It Work?</h4>
            <p><i>Breaker-Breaker!</i> uses the <a href="https://www.twilio.com/" target="_blank">Twilio</a> text messaging API to send messages entered into this app to cell phones (Currently it is configured to only send messages to my phone). The app is built using the <a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a> framework. "Sign In" and "Login" functions are handled by the Devise Rails gem. The website itself was styled using <a href="http://getbootstrap.com/" target="_blank">Twitter Bootstrap.</a></p>
            <br/>
          </div>
        </div>
      </div>
    </div>
<!--     <footer>
      <a href="http://www.jasonvogelsberg.com/" target="_blank"><em>&#169; J. Vogelsberg 2014 </em></a>
    </footer> -->
  </div>
</body>
</html>

app/views/messages/home.html.erb
<div class="row">
  <div class="intro">
    <br/>
    <h4><i><em>Breaker-Breaker!</em></i> lets you transmit text messages directly to your friends' phones, using only the stupendous black-magic of the interweb. If you're already a member, login to send a text message.</h4>
    <br/>
    <h4> If you aren't a member, it's quick, easy, and free to get started. Simply click the Sing Up link above.</h4>
    <br/>
	</div>
</div>

app/views/messages/index.html.erb
<h3><center>Your message was sent! Would you like to send another?</center></h3>
<br><br>

<h3><center> <%=  link_to "Send a New Message", new_message_path %> </center></h3>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Something went wrong:</p>
  <ul>
    <% message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<br><br>
<%= form_for @message do |f| %>
  <%= f.label :to %><br>
  <%= f.text_field :to, :value => "386-631-0258"%><br>
  <%= f.label :from %><br>
  <%= f.text_field :from, :value => "503-444-9779" %><br>
  <%= f.label :message %><br>
  <%= f.text_area :body, :size => 75  %><br>
  <%= f.submit %><br>
<% end %>